baseURL = "http://ando.fyi/"
languageCode = "en-us"
title = "Andrew's Blog"

theme = "ancri"
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 3