name = "Ancri"
license = "MIT"
licenselink = "https://github.com/Andoryuuta/ancri/blob/master/LICENSE"
description = ""
homepage = "https://github.com/Andoryuuta/ancri"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Andrew Gutekanst"
  homepage = "https://ando.fyi/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""